name: 检查更新

on:
  schedule:
  - cron: "0 */2 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: scoop检查更新
      shell: pwsh
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        .\bin\checkver.ps1 -u
    - name: Git Commit and Push
      if: success()
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.access_token }}
        push-branch: 'master'
        commit-message: '日常更新'
        name: GitHub Action
        email: action@github.com
