name: 检查更新

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: scoop检查更新
      shell: pwsh
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        .\bin\checkver.ps1 -u
    - name: 提交
      if: success()
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        $n = (git status -s | Measure-Object -Line)
        if($n.Lines -gt 0){ git commit -m "日常更新" -a}
    - run: git push
