name: 检查更新

on:
  schedule:
  - cron: "0 21 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: scoop检查更新
      shell: pwsh
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        .\bin\checkver.ps1 -u
    - name: 提交
      if: success()
      uses: github-actions-x/commit@v2.2
      with:
        commit_message: 日常更新
        push-branch: master
        github-token: ${{ secrets.access_token }}
