name: CI

on:
  schedule:
  - cron: "0 1 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-2019
    steps:
    - name: 安装scoop
      shell: powershell
      run: iwr -useb get.scoop.sh | iex
    - run: exit
    - uses: actions/checkout@master
    - name: 检查更新
      shell: powershell
      run: .\bin\checkver.ps1 -u
    - name: 提交
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "日常更新" -a
    - name: 推送
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.access_token }}
