name: CI

on:
  schedule:
  - cron: "0 1 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-2019
    steps:
    - name: 安装scoop
      shell: powershell
      run: |
        $env:SCOOP='d:\scoop'
        [environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')
        iwr -useb get.scoop.sh | iex
    - name: 安装仓库
      shell: powershell
      run: scoop bucket add fanlide https://github.com/fanlide/scoop-bucket.git
    - uses: d:\scoop\buckets\fanlide
    - name: 检查更新
      shell: powershell
      run: d:\scoop\buckets\fanlide\bin\checkver.ps1 -u
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "日常更新" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.access_token }}
