name: 检查更新

on:
  schedule:
  - cron: "0 21 * * ?"

jobs:
  check:
    name: check update
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: scoop检查更新
      shell: pwsh
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        .\bin\checkver.ps1 -u
    - name: 提交
      if: success()
      uses: peter-evans/commit-comment@v1.0.1
      with:
        token: ${{ secrets.access_token }}
        body: 日常更新
#      run: |
#        git config --local user.email "action@github.com"
#        git config --local user.name "GitHub Action"
#        git status -s
#        git commit -m "日常更新" -a
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.access_token }}
